language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  user: verginer
  password:
    secure: WjzTFC4ShqPFqvM8elT83dzu0PJLuQkCB5M2twaEnV0cwCv4i119FHB/op6DOVtcdBE802n5oGh+iaVjzxgDWy64yNZptz3T2JHK9jpgIduZdVONBsPQ9u86E1SALY4LA86tw5EhcvAvKWjBrv17c6Uin+kBY1C0b4CmOUcOiOajf1zyzEzyu7Ojy6HnzEUmdmO5E7Q2XdAQZneiXgc5ZUvxFI8lXv95+jtNzfW9uMjsm6wRI2qTGZEoEXD9eMuswV87S6Y7k+RmKxYzB1wY472VwFm6rD44fIK0MKINeaccoWqlcrz3qbsBCEvjlfigmShx9n37Kgn9ZR9a3G1nnArFX+aEOsTwwQakKvBGJlJrJ1EtMgkJVAXShk6d7uc9Gtm+uT1t755xZVpc0yc8Yu0VVuFMKY+fGTiIzDboqWuubxWYyi5+2ZFnn/rvyVQZLnvaHm3c9q5zcpXzzpJrnChgUedTrSfjsem7TfaFfpm0Ubfl87FRVMSt4wPkr9Og5Tf12TyVS31myz2AG1zUR+mLv0dpBiv7zdKglO1PtKT734o7TP0/h2ZiMc4pIiAvNyQzEaBKCMMJw3lRBQbba5iDP8Trii6Q/fRUzmPs9cm3011nnJjDFYFwhd48ilQnbQ42rue36f8egCYfnRENq/OgE1xRhlYIb5fS/Ckk1Wc=
  on:
    tags: true
