language: python
python:
- 3.6
- 3.5
install:
    - pip install -U tox-travis
    - pip install codacy-coverage
script:
    - tox
    - python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: verginer
  password:
    secure: vlOUVhxkfdPy31EZrKgWr7wNy3JwWsd3d0fFiVS6I2x5Si4J7gp3u6OR54d5HcebPNcWD0PFUpnXaCON3hWtkVHTahCn33wUz79sIdwWWTvP8uK3tqV1VlnTUrdi2LjFQJJokxIFdoxWoow2PBdiVnBciIm2CY0SBrpRN60MnAxzwIv6HcwE0gGPdyFqQsKCIvX2kR4u3B9A+/kNxmijgXQpONfA/6kqaR6ZQNpAO02hJDGGdIQeUKrZi9wyG30wxC10Mgqry48lBi+Bu5+q1KbEbTfF6t/qkt6S6q6VV0llLsIB6n4dlzAiJWAxxFXMrTdTx2RD/WT8UwH6RGbpeRYjXTweRGrAez97JW0pPGrcrTAGUVuucPV7qEUHGXLLvQcjeF1HQDOQZRHYvDCsiVrH2ftmb/kcqJu7l8lUjXRCkUaA9CGER2E75JvFILSxkowkg0ESNNYOsy+dRESPkNgpZ1ujMv8uZ5FgU8Ovokxp0DYcb45tQYjEh8fkwkETOUhxShgSMO+bSeVT629j5TeMgoO+s9Yg+M2re9JLKYzvPAOudYyEWspsH/g3fBD9ar4qvCMSBh5JbQwolyyrdZXw8wuIFb85CSFGt7y+kVyTKb29t/Cf00fqp97iwwwnwzaGKt+s57IVzwvoblDOllyXhaqR/lQwOtFL+zNI2z4=
  on:
    tags: true
